### ISSUE TITLE
Use official Fluent Bit Docker image 

### ISSUE THREAD

**Issue by edsiper** [kubeup/fluent-bit-aliyun#1]
Looking at the Dockerfile I found that you are building your own Fluent Bit image.

In order to keep your implementation aligned with our upstream work, would you please base your image on our fluent/fluent-bit:0.11 base image ?, on that way we make sure your deployments get our latest changes.

As a reference the 0.11 version is a long-term-support image, it only get bug fixes, no API changes so it's safe to use it.

**Comment by adieu** [comment]
Fixed by e247c4936cb35ba9a6c919ab49d25f49cdf6cf35
