### ISSUE TITLE
plugin don't run with timestamp

### ISSUE THREAD

**Issue by icloudnote** [kubeup/fluent-bit-aliyun#3]
when i compile plugin from source, i use "fluent-bit -c /etc/fluent-bit/fluent-bit.conf -e /etc/fluent-bit/out_sls.so" , the plugin doesn't work well.
output:
typeof timestampData is codec.RawExt{Tag:0x0, Data:[]uint8{0x59, 0x63, 0x52, 0x79, 0x0, 0x4, 0xb3, 0x85}, Value:interface {}(nil)}
Unable to convert timestamp: {Tag:0 Data:[89 99 82 121 0 4 179 133] Value:<nil>}
source code:
timestamp, ok := timestampData.Interface().(uint64)

**Comment by adieu** [comment]
can you check the version of fluent-bit? we're using fluent-bit 0.11 in the Dockerfile and it works fine.

If you're using a newer version, could you give me the commit id so that i could reproduce this issue.

Thanks a lot.

**Comment by icloudnote** [comment]
the version of fluent-bit is Fluent Bit v0.12.0; u can build it and to solve this issue.

**Comment by adieu** [comment]
it seems v0.12 is still in development. we'll support it as soon as it got released.

could you try using latest release v0.11.13 together with fluent-bit-aliyun?

**Comment by icloudnote** [comment]
thank you for you help, fluent-bit-aliyun can work well with v0.11.13;

**Comment by adieu** [comment]
i'll leave this issue open for v0.12

**Comment by nickwq** [comment]
Since fluent-bit has released v0.12， can we support the latest version?
