### ISSUE TITLE
use log service of aliyun

### ISSUE THREAD

**Issue by icloudnote** [kubeup/fluent-bit-aliyun#4]
how can i use "__topic__:" in log service of aliyun, 
fluent-bit tag  or other parameter
![image](https://user-images.githubusercontent.com/16571148/28129273-4b3c8fa6-6765-11e7-92e6-e54681d03764.png)
![image](https://user-images.githubusercontent.com/16571148/28129305-664107fa-6765-11e7-9823-34bc2a20a0e8.png)

**Comment by adieu** [comment]
I didn't quite get the purpose of `topic` so I set it to empty string in the plugin. Other tags set by the `input` or `filter` will be passed along to the backend.

Can you share us your user case with `topic`? Should it be set statically in the config file or extract certain tag from input?

**Comment by icloudnote** [comment]
i can understand it, if i want to use topic replace tags. what should i do. other tags i don't care.

**Comment by adieu** [comment]
This should be fixed by #5
