### ISSUE TITLE
add custom fields

### ISSUE THREAD

**Issue by icloudnote** [kubeup/fluent-bit-aliyun#6]
Is it possible to add custom fields in message? if fluent-bit running on many nodes and i want add some custom metadata, for example: hostname, what should i do;

**Comment by adieu** [comment]
One possible way is to use the `record_modifier` filter. You can find the documents at http://fluentbit.io/documentation/0.12/filter/record_modifier.html 

Currently fluent-bit 0.12 is still in development. We'll support it as soon as it got released. You could build your own `fluent-bit-aliyun` plugin with the latest version of fluent-bit if you cannot wait. If many people need 0.12, I can create a branch for it.

If there're some common fields which should be included for everybody, I'm happy to add them in the plugin to save people some time.
